//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynthUtil.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("voice_id")]
        public string proc_voiceid {
            get {
                return ((string)(this["proc_voiceid"]));
            }
            set {
                this["proc_voiceid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("text")]
        public string proc_text {
            get {
                return ((string)(this["proc_text"]));
            }
            set {
                this["proc_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_DelBetweenSymb {
            get {
                return ((bool)(this["t2ck_DelBetweenSymb"]));
            }
            set {
                this["t2ck_DelBetweenSymb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_DelSingleSymb {
            get {
                return ((bool)(this["t2ck_DelSingleSymb"]));
            }
            set {
                this["t2ck_DelSingleSymb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_Symb1 {
            get {
                return ((bool)(this["t2ck_Symb1"]));
            }
            set {
                this["t2ck_Symb1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_Symb2 {
            get {
                return ((bool)(this["t2ck_Symb2"]));
            }
            set {
                this["t2ck_Symb2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_Symb3 {
            get {
                return ((bool)(this["t2ck_Symb3"]));
            }
            set {
                this["t2ck_Symb3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_Symb4 {
            get {
                return ((bool)(this["t2ck_Symb4"]));
            }
            set {
                this["t2ck_Symb4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_Symb5 {
            get {
                return ((bool)(this["t2ck_Symb5"]));
            }
            set {
                this["t2ck_Symb5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_Symb6 {
            get {
                return ((bool)(this["t2ck_Symb6"]));
            }
            set {
                this["t2ck_Symb6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_CustomWordReplace {
            get {
                return ((bool)(this["t2ck_CustomWordReplace"]));
            }
            set {
                this["t2ck_CustomWordReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_DelEmptyText {
            get {
                return ((bool)(this["t2ck_DelEmptyText"]));
            }
            set {
                this["t2ck_DelEmptyText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_DelEmptyVT {
            get {
                return ((bool)(this["t2ck_DelEmptyVT"]));
            }
            set {
                this["t2ck_DelEmptyVT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t2ck_SortVoiceID {
            get {
                return ((bool)(this["t2ck_SortVoiceID"]));
            }
            set {
                this["t2ck_SortVoiceID"] = value;
            }
        }
    }
}
